name: PagesAction
on : 
  push:
    branches:
      - master
  pull_request:
    branches:
      - master
jobs:
  deployPages:
      runs-on: ubuntu-latest
      steps:
        - uses: actions/checkout@v2

        - name: Setup Node
          uses: actions/setup-node@v1
          with:
            node-version: '12'
            check-latest: true

        - run: npm install
#         - run: npm run test:unit
#         - run: npm run test:e2e
        - run: npm run build
          
        - name: Deploy
          uses: peaceiris/actions-gh-pages@v3.6.1
          with:
            publish_dir: ./dist 
